### ISSUE TITLE
I wanna help :)

### ISSUE THREAD

**Issue by ladasfeed** [mokuteki225/nest-websockets-chat-boilerplate#2]
Thank you for the amazing and clean example.
I would be glad to see browser side implementation. I can create folder `client` with a very simple implementation ( no frameworks, just js/html ). Having such example will make investigating that repo easier.
What do you think? 🙂

**Comment by vkondratiuk482** [comment]
Hey! 

Thank you for your feedback, but honestly when I was working on this project I didn't have that much skills and experience, and as for now I see a lot of bad practices, inconsistent code style, absence of proper architecture and so on. I don't delete this repo since I still think it might come in handy due to the lack of documentation on Websockets along with Nest. 

To sum it up I am no longer interested in maintaining this project, reviewing PRs and so on. Feel free to create your own fork and add all of the features you want :)
